### ISSUE TITLE
伺服器開啟失敗問題?

### ISSUE THREAD

**Issue by MARS0328** [Sarpendon/WindowsGSM.MythofEmpires#6]
LogGameMode: Display: Match State Changed from EnteringMap to WaitingToStart
LogInit: Display: Engine is initialized. Leaving FEngineLoop::Init()
LogOnline: Warning: OSS: Async task 'FOnlineAsyncTaskSteamCreateServer bWasSuccessful: 0' failed in 15.027047 seconds
LogAnimMontage: Warning: Playing a Montage (Stand_Eating_02-IP_Montage) for the wrong Skeleton (Elk_Y_Skeleton) instead of (Elk_F_Skeleton).
LogAnimMontage: Warning: Playing a Montage (Stand_Eating_01-IP_Montage) for the wrong Skeleton (Elk_Y_Skeleton) instead of (Elk_F_Skeleton).
是那邊有問題!?

**Comment by Sarpendon** [comment]
Download the new Plugin and try again it should work now
